name: kotlin_gephi_test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: fwilhe2/setup-kotlin@main
      - run: wget "https://github.com/gephi/gephi-toolkit/releases/download/v0.10.0/gephi-toolkit-0.10.0-all.jar"
      - run:  chmod +x ./run.sh
      - run: ./run.sh
